-- Seed idempotente: popula a tabela apenas quando ela estiver vazia.
INSERT INTO items (name, description, price)
SELECT name, description, price
FROM (
    VALUES
    ('Smartphone Galaxy A55', 'Celular Android com 128GB, tela AMOLED e camera tripla', 1899.90),
    ('iPhone 15 128GB', 'Smartphone Apple com chip A16, camera dupla e USB-C', 4999.00),
    ('Notebook Dell Inspiron 15', 'Notebook com Intel Core i5, 16GB RAM e SSD 512GB', 3499.90),
    ('Notebook Lenovo IdeaPad 3', 'Notebook para estudo e trabalho com Ryzen 5 e SSD 256GB', 2799.90),
    ('Monitor LG Ultrawide 29', 'Monitor IPS ultrawide Full HD de 29 polegadas', 1199.90),
    ('Monitor Samsung 24 Full HD', 'Monitor LED de 24 polegadas para escritorio e estudos', 699.90),
    ('Teclado Logitech K380', 'Teclado Bluetooth compacto para multiplos dispositivos', 219.90),
    ('Mouse Logitech MX Master 3S', 'Mouse sem fio ergonomico com sensor de alta precisao', 549.90),
    ('Headset HyperX Cloud Stinger', 'Headset gamer com microfone ajustavel e som estereo', 299.90),
    ('Fone JBL Tune 510BT', 'Fone Bluetooth dobravel com bateria de longa duracao', 249.90),
    ('Caixa JBL Go 3', 'Caixa de som Bluetooth portatil resistente a agua', 229.90),
    ('Smart TV LG 50 4K', 'Televisao 4K com webOS, HDR e comandos por voz', 2699.90),
    ('Smart TV Samsung 55 4K', 'Televisao Crystal UHD com aplicativos integrados', 2999.90),
    ('Chromecast Google TV', 'Dispositivo de streaming 4K com controle remoto', 399.90),
    ('Echo Dot 5 Geracao', 'Caixa inteligente com Alexa e som melhorado', 349.90),
    ('Kindle 11 Geracao', 'Leitor digital com tela antirreflexo e luz embutida', 499.90),
    ('Tablet Samsung Galaxy Tab A9', 'Tablet Android com tela de 8.7 polegadas e 64GB', 899.90),
    ('Carregador USB-C 30W', 'Carregador rapido compacto para celulares e tablets', 89.90),
    ('Cabo USB-C 2m', 'Cabo reforcado para carregamento e transferencia de dados', 39.90),
    ('Power Bank 20000mAh', 'Bateria externa com duas portas USB e carregamento rapido', 159.90),
    ('Roteador TP-Link Archer C6', 'Roteador dual band AC1200 para redes domesticas', 249.90),
    ('SSD Kingston NV2 1TB', 'SSD NVMe M.2 de alta velocidade para notebook e desktop', 399.90),
    ('HD Externo Seagate 2TB', 'Disco externo USB 3.0 para backup e arquivos', 499.90),
    ('Memoria RAM Kingston 16GB DDR4', 'Modulo de memoria DDR4 3200MHz para desktop', 289.90),
    ('Webcam Logitech C920', 'Webcam Full HD com microfone integrado para reunioes', 449.90),
    ('Cadeira Gamer ThunderX3', 'Cadeira ergonomica com apoio lombar e regulagem de altura', 1299.90),
    ('Mesa Digitalizadora Wacom One', 'Mesa para desenho digital e edicao de imagens', 399.90),
    ('Impressora Epson EcoTank L3250', 'Multifuncional tanque de tinta com Wi-Fi', 1199.90),
    ('Cartucho HP 664 Preto', 'Cartucho de tinta original HP preto', 69.90),
    ('Papel Sulfite A4 500 Folhas', 'Resma de papel branco 75g para impressao', 29.90),
    ('Cafeteira Nespresso Essenza Mini', 'Maquina compacta para cafe espresso em capsulas', 599.90),
    ('Cafeteira Oster Programavel', 'Cafeteira eletrica com timer e jarra de vidro', 249.90),
    ('Air Fryer Mondial 4L', 'Fritadeira eletrica sem oleo com cesto antiaderente', 399.90),
    ('Liquidificador Philips Walita', 'Liquidificador de 2 litros com varias velocidades', 199.90),
    ('Batedeira Arno Planetaria', 'Batedeira planetaria para massas leves e pesadas', 499.90),
    ('Sanduicheira Britania', 'Sanduicheira e grill com placas antiaderentes', 129.90),
    ('Panela Eletrica de Arroz', 'Panela eletrica com capacidade para 10 xicaras', 189.90),
    ('Micro-ondas Electrolux 31L', 'Micro-ondas com painel digital e funcao tira odor', 799.90),
    ('Geladeira Brastemp Frost Free', 'Refrigerador duplex frost free de 375 litros', 3299.90),
    ('Fogao Consul 4 Bocas', 'Fogao com acendimento automatico e forno amplo', 899.90),
    ('Lava e Seca Samsung 11kg', 'Lavadora e secadora com motor inverter', 4299.90),
    ('Aspirador Electrolux Vertical', 'Aspirador de po vertical 2 em 1 com filtro HEPA', 299.90),
    ('Ventilador Arno 40cm', 'Ventilador de mesa com tres velocidades', 179.90),
    ('Ar Condicionado LG Dual Inverter', 'Ar condicionado split 12000 BTUs quente e frio', 2499.90),
    ('Purificador de Agua Consul', 'Purificador compacto com filtro de alta eficiencia', 399.90),
    ('Jogo de Panelas Tramontina', 'Conjunto de panelas antiaderentes com 5 pecas', 349.90),
    ('Faqueiro Tramontina 24 Pecas', 'Faqueiro em aco inox para uso diario', 119.90),
    ('Conjunto de Copos 6 Unidades', 'Copos de vidro transparente para agua e suco', 49.90),
    ('Jogo de Toalhas Buddemeyer', 'Conjunto de toalhas de banho e rosto em algodao', 199.90),
    ('Edredom Casal Altenburg', 'Edredom macio para cama casal com enchimento leve', 249.90),
    ('Travesseiro Nasa Duoflex', 'Travesseiro viscoelastico com suporte cervical', 99.90),
    ('Colchao Ortobom Queen', 'Colchao queen size com molas ensacadas', 1899.90),
    ('Guarda-roupa 6 Portas', 'Guarda-roupa casal com gavetas e cabideiros', 1499.90),
    ('Sofa Retratil 3 Lugares', 'Sofa retratil e reclinavel em tecido suede', 2199.90),
    ('Rack para TV 65 Polegadas', 'Rack moderno com nichos e portas de correr', 599.90),
    ('Estante Livreiro 5 Prateleiras', 'Estante para livros e objetos decorativos', 349.90),
    ('Luminaria de Mesa LED', 'Luminaria articulada com tres niveis de brilho', 89.90),
    ('Tapete Sala 2x1.5m', 'Tapete decorativo macio para sala de estar', 299.90),
    ('Bicicleta Caloi Aro 29', 'Bicicleta mountain bike com freio a disco', 1599.90),
    ('Esteira Eletrica Movement', 'Esteira dobravel para caminhada e corrida leve', 2499.90),
    ('Halter Emborrachado 10kg', 'Par de halteres para treino funcional', 199.90),
    ('Colchonete de Yoga', 'Tapete em EVA antiderrapante para exercicios', 69.90),
    ('Tenis Nike Revolution 7', 'Tenis esportivo para corrida e caminhada', 349.90),
    ('Tenis Adidas Runfalcon', 'Tenis leve para uso diario e treino', 329.90),
    ('Mochila Dell Pro 15', 'Mochila para notebook com compartimentos acolchoados', 229.90),
    ('Mala Samsonite Pequena', 'Mala de bordo com rodinhas 360 graus', 699.90),
    ('Garrafa Stanley 950ml', 'Garrafa termica em aco inox para bebidas frias', 249.90),
    ('Relogio Casio G-Shock', 'Relogio resistente a impactos e agua', 599.90),
    ('Smartwatch Amazfit GTS', 'Relogio inteligente com monitoramento de saude', 799.90),
    ('Oculos Ray-Ban Aviador', 'Oculos de sol com armacao metalica e lentes escuras', 699.90),
    ('Perfume Natura Homem', 'Fragrancia masculina amadeirada para uso diario', 159.90),
    ('Shampoo Pantene 400ml', 'Shampoo hidratante para cabelos normais', 24.90),
    ('Protetor Solar Nivea FPS 60', 'Protetor solar corporal resistente a agua', 49.90),
    ('Escova Eletrica Oral-B', 'Escova dental eletrica recarregavel', 199.90),
    ('Barbeador Philips OneBlade', 'Barbeador eletrico para rosto e corpo', 249.90),
    ('Fralda Pampers Confort Sec', 'Pacote de fraldas descartaveis tamanho M', 59.90),
    ('Racao Golden Caes 15kg', 'Racao premium para caes adultos', 169.90),
    ('Areia Higienica Gatos 12kg', 'Areia granulada com controle de odores', 79.90),
    ('Coleira Antipulgas Seresto', 'Coleira antipulgas para caes de porte medio', 229.90),
    ('Livro Clean Code', 'Livro sobre boas praticas de desenvolvimento de software', 149.90),
    ('Livro O Programador Pragmatico', 'Guia pratico para evolucao profissional em tecnologia', 129.90),
    ('Caderno Moleskine Pontilhado', 'Caderno capa dura para anotacoes e estudos', 119.90),
    ('Caneta Bic Cristal Azul', 'Caixa com canetas esferograficas azuis', 19.90),
    ('Calculadora Casio FX-82MS', 'Calculadora cientifica para estudos e trabalho', 89.90),
    ('Controle Xbox Series', 'Controle sem fio para Xbox e PC', 449.90),
    ('PlayStation 5 Slim', 'Console Sony com SSD e controle DualSense', 3799.90),
    ('Nintendo Switch OLED', 'Console hibrido com tela OLED de 7 polegadas', 2399.90),
    ('Jogo EA Sports FC 26', 'Jogo de futebol para console de nova geracao', 349.90),
    ('Jogo The Legend of Zelda', 'Aventura para Nintendo Switch em midia fisica', 299.90),
    ('LEGO Classic Caixa Media', 'Conjunto de pecas LEGO para criacao livre', 249.90),
    ('Boneca Barbie Fashionista', 'Boneca colecionavel com roupas modernas', 99.90),
    ('Carrinho Hot Wheels 5 Pack', 'Conjunto com cinco miniaturas sortidas', 69.90),
    ('Quebra-cabeca 1000 Pecas', 'Puzzle com imagem decorativa para montar', 59.90),
    ('Violao Tagima Memphis', 'Violao acustico de nylon para iniciantes', 499.90),
    ('Teclado Musical Yamaha', 'Teclado portatil com timbres e ritmos variados', 1299.90),
    ('Microfone Fifine USB', 'Microfone condensador USB para gravacao e streaming', 299.90),
    ('Camera Canon EOS Rebel', 'Camera DSLR de entrada com lente 18-55mm', 3299.90),
    ('Tripe Fotografico 1.60m', 'Tripe leve em aluminio para cameras e celulares', 129.90),
    ('Ring Light LED 10 Polegadas', 'Iluminador circular com suporte para celular', 99.90),
    ('Kit Ferramentas Bosch', 'Maleta com furadeira, brocas e acessorios', 399.90)
) AS seed(name, description, price)
WHERE NOT EXISTS (SELECT 1 FROM items);

SELECT setval(pg_get_serial_sequence('items', 'id'), COALESCE((SELECT MAX(id) FROM items), 1), true);
